name = "깽판 마크서버"
author = "p1anbe2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1a8c04f0cb95f8a06e9fa1d42f38c55eae8c02db012458d32f80bd134e19cc4"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
