name = "깽판 마크서버"
author = "p1anbe2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91a48ec5231f77ee03989dc01ec879ba4bd98c12d590145e0332517ee2bb7bf7"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
